#
# host-ccache
#
HOST_CCACHE_VER    = 2020-05-25
HOST_CCACHE_DIR    = local
HOST_CCACHE_DEPS   = directories

HOST_CCACHE_BIN    = $(CCACHE)
HOST_CCACHE_BINDIR = $(HOST_DIR)/bin

HOST_CCACHE_LINKS = \
	ln -sf $(HOST_CCACHE_BIN) $(HOST_CCACHE_BINDIR)/cc; \
	ln -sf $(HOST_CCACHE_BIN) $(HOST_CCACHE_BINDIR)/gcc; \
	ln -sf $(HOST_CCACHE_BIN) $(HOST_CCACHE_BINDIR)/g++; \
	ln -sf $(HOST_CCACHE_BIN) $(HOST_CCACHE_BINDIR)/$(TARGET_CC); \
	ln -sf $(HOST_CCACHE_BIN) $(HOST_CCACHE_BINDIR)/$(TARGET_CXX)

HOST_CCACHE_ENV = \
	mkdir -p $(HOST_CCACHE_BINDIR); \
	mkdir -p $(HOST_DIR)/bin; \
	$(HOST_CCACHE_LINKS)

$(D)/host-ccache:
	$(START_BUILD)
	$(HOST_CCACHE_ENV)
	$(TOUCH)
